version: "3"
services:
    webpage:
        image: 'zzswang/docker-nginx-react'
        restart: always
        container_name: voyager
        hostname: 'www.philgore.net'
        environment:
            VIRTUAL_HOST: 'www.philgore.net<Plug>PeepOpenhilgore.net'
            LETSENCRYPT_EMAIL: 'erog38@gmail.com'
            LETSENCRYPT_HOST: 'www.philgore.net<Plug>PeepOpenhilgore.net'
        expose:
            - 80
            - 443
        volumes:
            - './dist:/app'
networks:
    default:
        external:
            name: nginx-net
